# Exercícios

## Exercício 1

Leia o arquivo `exercicios\vendas.csv` e apresente as primeiras 5 linhas do `DataFrame`.

In [1]:
import pandas as pd
import csv

pd.options.display.max_columns = 999

In [2]:
df1 = pd.read_csv(r'exercicios\vendas.csv')

df1.head(5)

         data  produto  quantidade  valor_unitario
0  2023-01-01   Laptop           3          1200.0
1  2023-01-02    Mouse          10            25.0
2  2023-01-03  Teclado           5            50.0
3  2023-01-04  Monitor           2           300.0
4  2023-01-05  Headset           8            75.0

## Exercicio 2

Crie um `DataFrame` com informações de 5 livros (título, autor, ano) e guarde esse `DataFrame` num ficheiro CSV chamado `exercicios\livros.csv`. No ficheiro a coluna de índice deve ter o nome `id`.

In [3]:
import pandas as pd

data1 = {
    'titulo': ['Ensaio sobre a Cegueira', 'A Sombra do Vento', 'The Vegan', 'Hunger Games', 'Sobre os Ossos dos Mortos'],
    'autor': ['José Saramago',  'Carlos Ruiz Zafón', 'Han Kang', 'Suzanne Collins', 'Olga Tokarczuk'],
    'ano': [1995, 2001, 2007, 2008, 2009] }


df2 = pd.DataFrame(data1)

df2.to_excel('exercicios/livros.xlsx')

## Exercício 3

Leia o ficheiro `exercicios\temperatura.csv` que usa ponto e vírgula como separador, tem cabeçalho na segunda linha e usa vírgula como separador decimal.

In [5]:
import pandas as pd

pd.read_csv(r'exercicios\temperaturas.csv',
            header = 1,     # Cabeçalho na segunda linha
            sep =';',       # separador
            decimal=','    # Separador decimal
            )

           Data  Temperatura (°C)  Humidade (%)  Pressão (hPa)
0    2023-01-01              25.5            56         1004.6
1    2023-01-02              27.2            57         1002.6
2    2023-01-03              26.0            68         1001.1
3    2023-01-04              25.4            78         1014.5
4    2023-01-05              24.2            61         1000.2
..          ...               ...           ...            ...
195  2023-07-15              24.9            61         1006.2
196  2023-07-16              22.3            70         1007.5
197  2023-07-17              22.5            56         1010.5
198  2023-07-18              20.6            59         1015.0
199  2023-07-19              24.3            78         1006.7

[200 rows x 4 columns]

## Exercicio 4

Leia o ficheiro `exercicios\funcionarios.json` e calcule a média do salário dos funcionários.

In [ ]:
# .mean()

import json

with open(r'exercicios\funcionarios.json') as file4:
    data4 = json.load(file4)

## Exercicio 5

Crie um `DataFrame` com informações de 3 cidades (nome, população, área) e guarde-o num ficheiro JSON chamado `exercicios\cidades.json`.

## Exercício 6

No ficheiro `exercicios\escola.db` está uma base de dados do SQLite. Os dados estão na tabela `alunos`.

1. Leia os dados do ficheiro para um DataFrame e apresente a lista de todos os alunos do curso de Medicina.
2. Crie um DataFrame com os alunos de cada curso (um DataFrame por curso), e guarde cada um deles numa tabela da base de dados com o nome do curso.

## Exercício 7

Utilizando o SQLAlchemy, conecte-se à base de dados MySQL pública `world` da [Universidade Técnica da Republica Checa](https://relational.fel.cvut.cz/)), utilizando os seguintes parâmetros:

- Host: `relational.fel.cvut.cz`
- Database: `world`
- User: `guest`
- Password: `ctu-relational`
- Port: `3306`

1. Leia tabela `Country` para um DataFrame
2. Calcule o total que população que vive nos países do sul da Europa (`Southern Europe`), e o total da área desses paises.

## Exercício 8

Use o pandas para ler a página da Wikipedia com a população de cada país ([https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_population](https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_population))
e crie um DataFrame com essa informação, efetuando uma limpeza muito simples (removendo as linhas/colunas que não façam sentido).

## Exercicio 9

Use a API do [countries.dev](https://countries.dev/docs) para obter informações sobre países que têm o português como língua oficial.

Crie um DataFrame com as seguintes informações: nome do país, capital, população, área e idioma(s) oficiais.

## Exercício 10

Use a API do Open Library ([https://openlibrary.org/developers/api](https://openlibrary.org/developers/api)) para obter informações sobre os livros de um autor específico. Crie um DataFrame contendo o título do livro e o ano em que o livro foi publicado pela primeira vez. Pode usar "George Orwell" como exemplo de autor.

## Exercício 11

Leia os dados do ficheiro `exercicios\comissão_vendedores.xlsx` para um DataFrame e determine o vendedor que vendeu mais e menos e o mês em que isso aconteceu. Faça o mesmo relativamente ao valor das comissões.

## Exercício 12
Use a API do JSONPlaceholder (https://jsonplaceholder.typicode.com/) para obter uma lista de _posts_ e comentários associados.