In [1]:
import pandas as pd

pd.options.display.max_columns = 999

In [2]:
URL = 'https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv'

df = pd.read_csv(URL)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

# Dicionário das colunas

- `PassengerID` - This is an Unique ID given to every passenger.
- `Survived` - 0 for deceased and 1 for survived
- `Pclass` - Passenger class ranging from 1 to 3
- `Name` - Passenger full name with honorifics
- `Sex` - Male or female
- `Age` - Age of the passenger
- `SibSp` - number of siblings or spouses on board related to the specific passenger
- `Parch` - number of parents or children on board related to the specific passenger
- `Ticket` - Ticket number
- `Fare` - Ticket fare
- `Cabin` - Cabin alloted to the passenger
- `Embarked` - Port of embarkation (C = Cherbourg; Q = Queenstown; S = Southampton)

In [10]:

# df.shape # mostra tamanho dos dados

# df.describe(include='all') # apresenta informaçoes estatisticas das colunas

# df.isna().sum() # registos representados por NA ou NAN

# df[df.isna().any(axis=1)].loc[60:65] # localizar colunas especificas

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
60,61,0,3,"Sirayanian, Mr. Orsen",male,22.0,0,0,2669,7.2292,NaN,C
61,62,1,1,"Icard, Miss. Amelie",female,38.0,0,0,113572,80.0000,B28,NaN
63,64,0,3,"Skoog, Master. Harald",male,4.0,3,2,347088,27.9000,NaN,S
64,65,0,1,"Stewart, Mr. Albert A",male,NaN,0,0,PC 17605,27.7208,NaN,C
65,66,1,3,"Moubarek, Master. Gerios",male,NaN,1,1,2661,15.2458,NaN,C

In [12]:
# Coluna EMBARKED

df[df['Embarked'].isna()]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
61,62,1,1,"Icard, Miss. Amelie",female,38.0,0,0,113572,80.0,B28,NaN
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0,B28,NaN

In [13]:
df2 = df.copy()

df2['Embarked'].unique()

<StringArray>
['S', 'C', 'Q', nan]
Length: 4, dtype: str

In [ ]:
df2['Embarked'] = df2['Embarked'].fillna('Unknown') # trocar na por unknown

df2['Embarked'].unique()

<StringArray>
['S', 'C', 'Q', 'Unknown']
Length: 4, dtype: str

In [18]:
df = df.dropna(subset = 'Embarked')
df.shape

(889, 12)

In [ ]:
df['Age'].mean() # media

np.float64(29.69911764705882)

In [ ]:
df['Age'].median() # mediana

np.float64(28.0)

In [20]:
df['Age'].mode() # moda

0    24.0
Name: Age, dtype: float64

In [25]:
mediana = df['Age'].median()

df3 = df.copy()

df3['Age'] = df3['Age'].fillna(mediana)

df3['Age'].median(), df3['Age'].mean()

(np.float64(28.0), np.float64(29.315151856017994))

In [27]:
df.groupby('Sex')['Age']

In [29]:
median_age_pclass = df.groupby(['Sex','Pclass'])['Age'].transform('median')

median_age_pclass

0      25.0
1      35.0
2      21.5
3      35.0
4      25.0
       ...
886    30.0
887    35.0
888    21.5
889    40.0
890    25.0
Name: Age, Length: 889, dtype: float64

In [30]:
df.groupby(['Sex', 'Pclass'])['Age'].describe()

               count       mean        std   min     25%   50%    75%   max
Sex    Pclass
female 1        83.0  34.240964  13.430572  2.00  23.000  35.0  44.00  63.0
       2        74.0  28.722973  12.872702  2.00  22.250  28.0  36.00  57.0
       3       102.0  21.750000  12.729964  0.75  14.125  21.5  29.75  63.0
male   1       101.0  41.281386  15.139570  0.92  30.000  40.0  51.00  80.0
       2        99.0  30.740707  14.793894  0.67  23.000  30.0  36.75  70.0
       3       253.0  26.507589  12.159514  0.42  20.000  25.0  33.00  74.0